apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: p1as-grafana-chart
chartName: p1as-grafana
repo: oci://${ECR_REGISTRY_NAME}/dev
version: v2.2-release-branch-latest
releaseName: p1as-grafana
namespace: prometheus
includeCRDs: true
valuesFile: grafana-values.yaml
