# Customer-hub overrides for p1as-observability.
#
# ### prometheus-agent ###
# 1. opensearch-grafana-credentials: The secret is created by p14c-integration in os-controller-manager which only
#    runs in non-chub envs. Remove volume mounts so prometheus-agent can start without the secret in customer-hub envs.
prometheus-agent:
  server:
    # Override extraVolumes and extraVolumeMounts to empty arrays. Since customer-hub does not deploy OpenSearch,
    # the opensearch-grafana-credentials secret will not exist and clearing these mounts prevents pod startup failure.
    extraVolumes: []
    extraVolumeMounts: []

nri-bundle:
  newrelic-prometheus-agent:
    extraVolumes: []
    extraVolumeMounts: []

# CHUB does not run OpenSearch. Disabling both subcharts prevents the operator
# and cluster CR from rendering any resources.
opensearch-cluster:
  enabled: false

opensearch-operator:
  enabled: false
