grafana-operator:
  namespaceScope: true
  fullnameOverride: grafana-operator-controller-manager

  additionalLabels:
    app: grafana-operator-controller-manager
    control-plane: grafana-operator-controller-manager

  image:
    repository: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/grafana-operator/grafana-operator
    pullPolicy: Always
    tag: v5.6.0

  serviceAccount:
    name: grafana-operator-controller-manager

  securityContext:
    allowPrivilegeEscalation: false

  resources:
    limits:
      cpu: 200m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 20Mi

grafana:
  image:
    repository: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/grafana/grafana
    tag: 10.1.0

  env:
    gfInstallPlugins: "grafana-opensearch-datasource 2.10.1"

  resources:
    limits:
      cpu: "1"
      memory: 2500Mi
    requests:
      cpu: 100m
      memory: 100Mi

  service:
    name: grafana
    labels:
      app: grafana
    selector:
      app: grafana
    port: 3000
    portName: grafana
    clusterIP: None

  datasources:
    - name: prometheus
      datasource:
        name: prometheus
        type: prometheus
        access: proxy
        editable: true
        isDefault: true
        url: http://prometheus:9090
        uid: P1809F7CD0C75ACF3

    - name: os-pa-audit
      datasource:
        name: OS-PA-Audit
        type: grafana-opensearch-datasource
        access: proxy
        basicAuth: true
        basicAuthUser: ${username}
        isDefault: false
        secureJsonData:
          basicAuthPassword: ${password}
        url: https://opensearch-cluster-headless.elastic-stack-logging.svc.cluster.local:9200
        jsonData:
          database: pa-audit-ro
          esVersion: 8.0.0
          flavor: opensearch
          pplEnabled: true
          timeField: '@timestamp'
          tlsSkipVerify: true
          version: 2.8.0
        uid: muQHLUs4k
      valuesFrom:
        - targetPath: basicAuthUser
          valueFrom:
            secretKeyRef:
              name: opensearch-grafana-credentials
              key: username
        - targetPath: secureJsonData.basicAuthPassword
          valueFrom:
            secretKeyRef:
              name: opensearch-grafana-credentials
              key: password

    - name: os-pf-audit
      datasource:
        name: OS-PF-Audit
        type: grafana-opensearch-datasource
        access: proxy
        basicAuth: true
        basicAuthUser: ${username}
        isDefault: false
        secureJsonData:
          basicAuthPassword: ${password}
        url: https://opensearch-cluster-headless.elastic-stack-logging.svc.cluster.local:9200
        jsonData:
          database: pf-audit-*
          esVersion: 8.0.0
          flavor: opensearch
          pplEnabled: true
          timeField: '@timestamp'
          tlsSkipVerify: true
          version: 2.8.0
        uid: xCysL8y4z
      valuesFrom:
        - targetPath: basicAuthUser
          valueFrom:
            secretKeyRef:
              name: opensearch-grafana-credentials
              key: username
        - targetPath: secureJsonData.basicAuthPassword
          valueFrom:
            secretKeyRef:
              name: opensearch-grafana-credentials
              key: password

  folders:
    - name: kubernetesdashboards
      title: Kubernetes

    - name: monitoringdashboards
      title: Monitoring

    - name: pingdashboards
      title: Ping
      permissions: |-
        {
          "items": [
            {
              "role": "Admin",
              "permission": 4
            },
            {
              "role": "Editor",
              "permission": 4
            }
          ]
        }
