apiVersion: v1
kind: Service
metadata:
  name: fluentbit-exporter
  namespace: elastic-stack-logging
  labels:
    app: fluentbit-storage-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8089"
spec:
  selector:
    k8s-app: fluent-bit
  ports:
    - name: exporter-metrics
      protocol: TCP
      port: 8089
      targetPort: 8089
